<a href="https://colab.research.google.com/github/11249a389-ui/11249A389.DST-record/blob/main/myprojectmodel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [ ]:
#creating a dataset
#creating a dataset
data = {
    "Roll_No": list(range(101,131)),
    "Name": [
        "Rahul","koushik","Naga","Dheeraj",
        "Anjali", "vikram", "Pooja", "Harika",
        "sanjana", "varun","muni", "Akash",
        "Manoj", "Abhishek", "Teja", "Deepa",
        "Neha", "Abhishek", "pramod", "Abhi",
        "Rahul","koushik","Naga","Dheeraj",
        "Anjali", "vikram", "Pooja", "Harika",
        "sanjana", "varun"
    ],
    "CGPA":  [
        8.7,9.2,6.8,8.4,7.2,
        7.5,9.3,6.9,8.1,7.8,
        9.0,7.1,8.8,6.5,8.6,
        7.7,9.2,7.8,6.3,6.7,
        8.9,7.4,9.4,6.9,8.2,
        7.6,9.1,7.3,8.5,6.6
    ],
    "Skills": [
        8,5,9,3,7,
        6,9,4,7,6,
        8,5,8,3,7,
        6,9,4,7,3,
        8,5,9,4,7,
        6,8,5,1,3
    ],
    "Projects": [
        3,1,4,0,3,
        2,4,1,2,2,
        3,1,3,0,3,
        2,4,1,2,1,
        3,2,4,1,3,
        2,3,1,0,0
    ],
    "Internships": [
    1,0,2,0,1,
    1,2,0,1,0,
    1,0,1,0,1,
    1,2,0,1,0,
    1,2,0,1,0,
    1,1,2,0,1
],


    "Certifications": [
        4,2,5,1,3,
        2,5,1,3,2,
        4,2,4,1,3,
        3,5,1,3,1,
        4,2,5,1,3,
        2,4,2,0,1
    ],
    "DSA_Score": [
        82,91,48,76,61,
        68,94,52,74,65,
        86,59,45,52,95,
        70,92,50,73,55,
        84,63,95,49,77,
        69,88,60,22,47
    ],
    "Placed": [
        1,0,1,0,1,
        0,1,0,1,0,
        1,0,1,0,1,
        0,1,0,1,0,
        1,0,1,0,1,
        0,1,0,1,0
    ]
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df = pd.DataFrame(data)

ValueError: All arrays must be of the same length

In [ ]:
df = pd.DataFrame(data)

In [ ]:
#creating a dataframe
df = pd.DataFrame(data)
print(df)

    Roll_No      Name  CGPA  ...  Certifications  DSA_Score  Placed
0       101     Rahul   8.7  ...               4         82       1
1       102   koushik   9.2  ...               2         91       0
2       103      Naga   6.8  ...               5         48       1
3       104   Dheeraj   8.4  ...               1         76       0
4       105    Anjali   7.2  ...               3         61       1
5       106    vikram   7.5  ...               2         68       0
6       107     Pooja   9.3  ...               5         94       1
7       108    Harika   6.9  ...               1         52       0
8       109   sanjana   8.1  ...               3         74       1
9       110     varun   7.8  ...               2         65       0
10      111      muni   9.0  ...               4         86       1
11      112     Akash   7.1  ...               2         59       0
12      113     Manoj   8.8  ...               4         45       1
13      114  Abhishek   6.5  ...               1         52       0
14      115      Teja   8.6  ...               3         95       1
15      116     Deepa   7.7  ...               3         70       0
16      117      Neha   9.2  ...               5         92       1
17      118  Abhishek   7.8  ...               1         50       0
18      119    pramod   6.3  ...               3         73       1
19      120      Abhi   6.7  ...               1         55       0
20      121     Rahul   8.9  ...               4         84       1
21      122   koushik   7.4  ...               2         63       0
22      123      Naga   9.4  ...               5         95       1
23      124   Dheeraj   6.9  ...               1         49       0
24      125    Anjali   8.2  ...               3         77       1
25      126    vikram   7.6  ...               2         69       0
26      127     Pooja   9.1  ...               4         88       1
27      128    Harika   7.3  ...               2         60       0
28      129   sanjana   8.5  ...               0         22       1
29      130     varun   6.6  ...               1         47       0

[30 rows x 9 columns]

In [ ]:
# select the features(x)
#Roll number and name are not used for prediction
X = df[
    [
        "CGPA", "Skills", "Projects",
        "Internships", "Certifications",
        "DSA_Score"
    ]
    ]

In [ ]:
X

    CGPA  Skills  Projects  Internships  Certifications  DSA_Score
0    8.7       8         3            1               4         82
1    9.2       5         1            0               2         91
2    6.8       9         4            2               5         48
3    8.4       3         0            0               1         76
4    7.2       7         3            1               3         61
5    7.5       6         2            1               2         68
6    9.3       9         4            2               5         94
7    6.9       4         1            0               1         52
8    8.1       7         2            1               3         74
9    7.8       6         2            0               2         65
10   9.0       8         3            1               4         86
11   7.1       5         1            0               2         59
12   8.8       8         3            1               4         45
13   6.5       3         0            0               1         52
14   8.6       7         3            1               3         95
15   7.7       6         2            1               3         70
16   9.2       9         4            2               5         92
17   7.8       4         1            0               1         50
18   6.3       7         2            1               3         73
19   6.7       3         1            0               1         55
20   8.9       8         3            1               4         84
21   7.4       5         2            2               2         63
22   9.4       9         4            0               5         95
23   6.9       4         1            1               1         49
24   8.2       7         3            0               3         77
25   7.6       6         2            1               2         69
26   9.1       8         3            1               4         88
27   7.3       5         1            2               2         60
28   8.5       1         0            0               0         22
29   6.6       3         0            1               1         47

In [ ]:
#select the target/label(y)
# 1 = placed
# 0 = Not placed
y= df["Placed"]

In [ ]:
y

0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     0
8     1
9     0
10    1
11    0
12    1
13    0
14    1
15    0
16    1
17    0
18    1
19    0
20    1
21    0
22    1
23    0
24    1
25    0
26    1
27    0
28    1
29    0
Name: Placed, dtype: int64

In [ ]:
#splitting the data into train and test data
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
print("Training students:", len(X_train))
print("Testing students:",len(X_test))

Training students: 24
Testing students: 6

In [ ]:
#create the machine learning model
model = DecisionTreeClassifier(random_state=42)

In [ ]:
# Train the model
model.fit(X_train, y_train)
print("\nModel training completed!")

Model training completed!

In [ ]:
# test the model
predictions = model.predict(X_test)
print("\nActual vlaues:", list(y_test))
print("Predicted values:", list(predictions))

Actual vlaues: [0, 0, 0, 0, 1, 0]
Predicted values: [np.int64(0), np.int64(1), np.int64(0), np.int64(0), np.int64(1), np.int64(0)]

In [ ]:
#testing accuracy
accuracy = accuracy_score(y_test,predictions)

In [ ]:
accuracy

0.8333333333333334

In [ ]:
#creating a new data
# .create a completely new student
new_student = pd.DataFrame([{
    "CGPA": 8.5,
    "Skills": 7,
    "Projects": 2,
    "Internships": 1,
    "Certifications": 3,
    "DSA_Score": 8.5
}])

In [ ]:
new_student

   CGPA  Skills  Projects  Internships  Certifications  DSA_Score
0   8.5       7         2            1               3        8.5

In [ ]:
#predicting new student output
prediction = model.predict(new_student)

In [ ]:
prediction

array([1])

In [ ]:
if prediction[0] == 1:
  print("\nPrediction: PLACED")
else:
  print("\nPrediction: NOT PLACED")

Prediction: PLACED